/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const Time = IDL.Int;
export const WorkoutDay = IDL.Record({
  'exercises' : IDL.Vec(Exercise),
  'completionTimestamp' : IDL.Opt(Time),
  'isComplete' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DayLog = IDL.Record({
  'date' : IDL.Text,
  'isComplete' : IDL.Bool,
});
export const WeeklyLog = IDL.Record({
  'days' : IDL.Vec(DayLog),
  'user' : IDL.Principal,
});
export const WorkoutEntry = IDL.Record({
  'user' : IDL.Principal,
  'workoutDay' : IDL.Opt(WorkoutDay),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ScheduledWorkout = IDL.Record({
  'date' : IDL.Text,
  'workoutDay' : WorkoutDay,
});
export const SetLog = IDL.Record({
  'weight' : IDL.Float64,
  'reps' : IDL.Nat,
  'exerciseName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addWorkoutDay' : IDL.Func([IDL.Principal, WorkoutDay], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeWorkoutDay' : IDL.Func([], [], []),
  'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getAllWeeklyLogs' : IDL.Func([], [IDL.Vec(WeeklyLog)], ['query']),
  'getAllWorkouts' : IDL.Func([], [IDL.Vec(WorkoutEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExerciseByName' : IDL.Func([IDL.Text], [Exercise], ['query']),
  'getScheduledWorkouts' : IDL.Func([], [IDL.Vec(ScheduledWorkout)], ['query']),
  'getSetLogs' : IDL.Func([], [IDL.Vec(SetLog)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyLog' : IDL.Func([], [WeeklyLog], ['query']),
  'getWorkoutDay' : IDL.Func([], [IDL.Opt(WorkoutDay)], ['query']),
  'getWorkoutDayByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(WorkoutDay)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logSet' : IDL.Func([SetLog], [], []),
  'logWorkoutDay' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scheduleWorkoutDay' : IDL.Func(
      [IDL.Principal, IDL.Text, WorkoutDay],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Exercise = IDL.Record({
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const Time = IDL.Int;
  const WorkoutDay = IDL.Record({
    'exercises' : IDL.Vec(Exercise),
    'completionTimestamp' : IDL.Opt(Time),
    'isComplete' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DayLog = IDL.Record({ 'date' : IDL.Text, 'isComplete' : IDL.Bool });
  const WeeklyLog = IDL.Record({
    'days' : IDL.Vec(DayLog),
    'user' : IDL.Principal,
  });
  const WorkoutEntry = IDL.Record({
    'user' : IDL.Principal,
    'workoutDay' : IDL.Opt(WorkoutDay),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ScheduledWorkout = IDL.Record({
    'date' : IDL.Text,
    'workoutDay' : WorkoutDay,
  });
  const SetLog = IDL.Record({
    'weight' : IDL.Float64,
    'reps' : IDL.Nat,
    'exerciseName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addWorkoutDay' : IDL.Func([IDL.Principal, WorkoutDay], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeWorkoutDay' : IDL.Func([], [], []),
    'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getAllWeeklyLogs' : IDL.Func([], [IDL.Vec(WeeklyLog)], ['query']),
    'getAllWorkouts' : IDL.Func([], [IDL.Vec(WorkoutEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExerciseByName' : IDL.Func([IDL.Text], [Exercise], ['query']),
    'getScheduledWorkouts' : IDL.Func(
        [],
        [IDL.Vec(ScheduledWorkout)],
        ['query'],
      ),
    'getSetLogs' : IDL.Func([], [IDL.Vec(SetLog)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyLog' : IDL.Func([], [WeeklyLog], ['query']),
    'getWorkoutDay' : IDL.Func([], [IDL.Opt(WorkoutDay)], ['query']),
    'getWorkoutDayByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WorkoutDay)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logSet' : IDL.Func([SetLog], [], []),
    'logWorkoutDay' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scheduleWorkoutDay' : IDL.Func(
        [IDL.Principal, IDL.Text, WorkoutDay],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };