/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DayLog { 'date' : string, 'isComplete' : boolean }
export interface Exercise {
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
  'description' : string,
  'category' : string,
  'videoUrl' : string,
}
export interface ScheduledWorkout { 'date' : string, 'workoutDay' : WorkoutDay }
export interface SetLog {
  'weight' : number,
  'reps' : bigint,
  'exerciseName' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyLog { 'days' : Array<DayLog>, 'user' : Principal }
export interface WorkoutDay {
  'exercises' : Array<Exercise>,
  'completionTimestamp' : [] | [Time],
  'isComplete' : boolean,
}
export interface WorkoutEntry {
  'user' : Principal,
  'workoutDay' : [] | [WorkoutDay],
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addWorkoutDay' : ActorMethod<[Principal, WorkoutDay], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeWorkoutDay' : ActorMethod<[], undefined>,
  'getAllExercises' : ActorMethod<[], Array<Exercise>>,
  'getAllWeeklyLogs' : ActorMethod<[], Array<WeeklyLog>>,
  'getAllWorkouts' : ActorMethod<[], Array<WorkoutEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExerciseByName' : ActorMethod<[string], Exercise>,
  'getScheduledWorkouts' : ActorMethod<[], Array<ScheduledWorkout>>,
  'getSetLogs' : ActorMethod<[], Array<SetLog>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyLog' : ActorMethod<[], WeeklyLog>,
  'getWorkoutDay' : ActorMethod<[], [] | [WorkoutDay]>,
  'getWorkoutDayByDate' : ActorMethod<[string], [] | [WorkoutDay]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logSet' : ActorMethod<[SetLog], undefined>,
  'logWorkoutDay' : ActorMethod<[string, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'scheduleWorkoutDay' : ActorMethod<
    [Principal, string, WorkoutDay],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];