/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    name: string;
    reps: bigint;
    sets: bigint;
    description: string;
    category: string;
    videoUrl: string;
}
export type Time = bigint;
export interface WeeklyLog {
    days: Array<DayLog>;
    user: Principal;
}
export interface DayLog {
    date: string;
    isComplete: boolean;
}
export interface ScheduledWorkout {
    date: string;
    workoutDay: WorkoutDay;
}
export interface SetLog {
    weight: number;
    reps: bigint;
    exerciseName: string;
}
export interface WorkoutEntry {
    user: Principal;
    workoutDay?: WorkoutDay;
}
export interface WorkoutDay {
    exercises: Array<Exercise>;
    completionTimestamp?: Time;
    isComplete: boolean;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addWorkoutDay(user: Principal, workoutDay: WorkoutDay): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeWorkoutDay(): Promise<void>;
    getAllExercises(): Promise<Array<Exercise>>;
    getAllWeeklyLogs(): Promise<Array<WeeklyLog>>;
    getAllWorkouts(): Promise<Array<WorkoutEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExerciseByName(name: string): Promise<Exercise>;
    getScheduledWorkouts(): Promise<Array<ScheduledWorkout>>;
    getSetLogs(): Promise<Array<SetLog>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeeklyLog(): Promise<WeeklyLog>;
    getWorkoutDay(): Promise<WorkoutDay | null>;
    getWorkoutDayByDate(date: string): Promise<WorkoutDay | null>;
    isCallerAdmin(): Promise<boolean>;
    logSet(setLog: SetLog): Promise<void>;
    logWorkoutDay(date: string, isComplete: boolean): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    scheduleWorkoutDay(user: Principal, date: string, workoutDay: WorkoutDay): Promise<void>;
}
import type { Exercise as _Exercise, ScheduledWorkout as _ScheduledWorkout, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, WorkoutDay as _WorkoutDay, WorkoutEntry as _WorkoutEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addWorkoutDay(arg0: Principal, arg1: WorkoutDay): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkoutDay(arg0, to_candid_WorkoutDay_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkoutDay(arg0, to_candid_WorkoutDay_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeWorkoutDay(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeWorkoutDay();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeWorkoutDay();
            return result;
        }
    }
    async getAllExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExercises();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExercises();
            return result;
        }
    }
    async getAllWeeklyLogs(): Promise<Array<WeeklyLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWeeklyLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWeeklyLogs();
            return result;
        }
    }
    async getAllWorkouts(): Promise<Array<WorkoutEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkouts();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkouts();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExerciseByName(arg0: string): Promise<Exercise> {
        if (this.processError) {
            try {
                const result = await this.actor.getExerciseByName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExerciseByName(arg0);
            return result;
        }
    }
    async getScheduledWorkouts(): Promise<Array<ScheduledWorkout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScheduledWorkouts();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScheduledWorkouts();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSetLogs(): Promise<Array<SetLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSetLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSetLogs();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyLog(): Promise<WeeklyLog> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyLog();
            return result;
        }
    }
    async getWorkoutDay(): Promise<WorkoutDay | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutDay();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutDay();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutDayByDate(arg0: string): Promise<WorkoutDay | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutDayByDate(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutDayByDate(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logSet(arg0: SetLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logSet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logSet(arg0);
            return result;
        }
    }
    async logWorkoutDay(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkoutDay(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkoutDay(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async scheduleWorkoutDay(arg0: Principal, arg1: string, arg2: WorkoutDay): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleWorkoutDay(arg0, arg1, to_candid_WorkoutDay_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleWorkoutDay(arg0, arg1, to_candid_WorkoutDay_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_ScheduledWorkout_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScheduledWorkout): ScheduledWorkout {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutDay_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutDay): WorkoutDay {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutEntry_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutEntry): WorkoutEntry {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkoutDay]): WorkoutDay | null {
    return value.length === 0 ? null : from_candid_WorkoutDay_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exercises: Array<_Exercise>;
    completionTimestamp: [] | [_Time];
    isComplete: boolean;
}): {
    exercises: Array<Exercise>;
    completionTimestamp?: Time;
    isComplete: boolean;
} {
    return {
        exercises: value.exercises,
        completionTimestamp: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.completionTimestamp)),
        isComplete: value.isComplete
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    workoutDay: _WorkoutDay;
}): {
    date: string;
    workoutDay: WorkoutDay;
} {
    return {
        date: value.date,
        workoutDay: from_candid_WorkoutDay_n9(_uploadFile, _downloadFile, value.workoutDay)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: Principal;
    workoutDay: [] | [_WorkoutDay];
}): {
    user: Principal;
    workoutDay?: WorkoutDay;
} {
    return {
        user: value.user,
        workoutDay: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.workoutDay))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScheduledWorkout>): Array<ScheduledWorkout> {
    return value.map((x)=>from_candid_ScheduledWorkout_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutEntry>): Array<WorkoutEntry> {
    return value.map((x)=>from_candid_WorkoutEntry_n6(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutDay_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutDay): _WorkoutDay {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    exercises: Array<Exercise>;
    completionTimestamp?: Time;
    isComplete: boolean;
}): {
    exercises: Array<_Exercise>;
    completionTimestamp: [] | [_Time];
    isComplete: boolean;
} {
    return {
        exercises: value.exercises,
        completionTimestamp: value.completionTimestamp ? candid_some(value.completionTimestamp) : candid_none(),
        isComplete: value.isComplete
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
